// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nuages.Fido2.Storage.EntifyFramework.MySql;

#nullable disable

namespace Nuages.Fido2.Storage.EntifyFramework.MySql.Migrations
{
    [DbContext(typeof(IdentityFido2MySqlDbContext))]
    [Migration("20220315131358_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Nuages.Identity.Fido2.Storage.EntityFramework.Fido2Credential", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("CredType")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptorIdBase64")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DescriptorJson")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptorTransports")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptorType")
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("SignatureCounter")
                        .HasColumnType("int unsigned");

                    b.Property<byte[]>("UserHandle")
                        .HasColumnType("longblob");

                    b.Property<string>("UserHandleBase64")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("UserId")
                        .HasColumnType("longblob");

                    b.Property<string>("UserIdBase64")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DescriptorIdBase64")
                        .IsUnique();

                    b.HasIndex("UserHandleBase64");

                    b.HasIndex("UserIdBase64");

                    b.HasIndex("UserIdBase64", "DescriptorIdBase64");

                    b.ToTable("Fido2Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
